/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AuditTrail {
  export type AuditRecordStruct = {
    auditId: BytesLike;
    userId: BytesLike;
    eventType: BytesLike;
    riskLevel: BigNumberish;
    eventHash: BytesLike;
    timestamp: BigNumberish;
    writer: AddressLike;
    exists: boolean;
  };

  export type AuditRecordStructOutput = [
    auditId: string,
    userId: string,
    eventType: string,
    riskLevel: bigint,
    eventHash: string,
    timestamp: bigint,
    writer: string,
    exists: boolean
  ] & {
    auditId: string;
    userId: string;
    eventType: string;
    riskLevel: bigint;
    eventHash: string;
    timestamp: bigint;
    writer: string;
    exists: boolean;
  };
}

export interface AuditTrailInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditCount"
      | "backendWriters"
      | "getAudit"
      | "getAuditIdAt"
      | "owner"
      | "recordAudit"
      | "setBackendWriter"
      | "transferOwnership"
      | "verifyAudit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditRecorded"
      | "BackendWriterUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auditCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backendWriters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getAudit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAuditIdAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAudit",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendWriter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAudit",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "backendWriters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAudit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuditIdAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendWriter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAudit",
    data: BytesLike
  ): Result;
}

export namespace AuditRecordedEvent {
  export type InputTuple = [
    auditId: BytesLike,
    userId: BytesLike,
    eventType: BytesLike,
    riskLevel: BigNumberish,
    eventHash: BytesLike,
    timestamp: BigNumberish,
    writer: AddressLike
  ];
  export type OutputTuple = [
    auditId: string,
    userId: string,
    eventType: string,
    riskLevel: bigint,
    eventHash: string,
    timestamp: bigint,
    writer: string
  ];
  export interface OutputObject {
    auditId: string;
    userId: string;
    eventType: string;
    riskLevel: bigint;
    eventHash: string;
    timestamp: bigint;
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BackendWriterUpdatedEvent {
  export type InputTuple = [writer: AddressLike, allowed: boolean];
  export type OutputTuple = [writer: string, allowed: boolean];
  export interface OutputObject {
    writer: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditTrail extends BaseContract {
  connect(runner?: ContractRunner | null): AuditTrail;
  waitForDeployment(): Promise<this>;

  interface: AuditTrailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditCount: TypedContractMethod<[], [bigint], "view">;

  backendWriters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAudit: TypedContractMethod<
    [auditId: BytesLike],
    [AuditTrail.AuditRecordStructOutput],
    "view"
  >;

  getAuditIdAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordAudit: TypedContractMethod<
    [
      auditId: BytesLike,
      userId: BytesLike,
      eventType: BytesLike,
      riskLevel: BigNumberish,
      eventHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setBackendWriter: TypedContractMethod<
    [writer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyAudit: TypedContractMethod<
    [auditId: BytesLike, expectedEventHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "backendWriters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAudit"
  ): TypedContractMethod<
    [auditId: BytesLike],
    [AuditTrail.AuditRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditIdAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAudit"
  ): TypedContractMethod<
    [
      auditId: BytesLike,
      userId: BytesLike,
      eventType: BytesLike,
      riskLevel: BigNumberish,
      eventHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBackendWriter"
  ): TypedContractMethod<
    [writer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAudit"
  ): TypedContractMethod<
    [auditId: BytesLike, expectedEventHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuditRecorded"
  ): TypedContractEvent<
    AuditRecordedEvent.InputTuple,
    AuditRecordedEvent.OutputTuple,
    AuditRecordedEvent.OutputObject
  >;
  getEvent(
    key: "BackendWriterUpdated"
  ): TypedContractEvent<
    BackendWriterUpdatedEvent.InputTuple,
    BackendWriterUpdatedEvent.OutputTuple,
    BackendWriterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AuditRecorded(bytes32,bytes32,bytes32,uint8,bytes32,uint256,address)": TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;
    AuditRecorded: TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;

    "BackendWriterUpdated(address,bool)": TypedContractEvent<
      BackendWriterUpdatedEvent.InputTuple,
      BackendWriterUpdatedEvent.OutputTuple,
      BackendWriterUpdatedEvent.OutputObject
    >;
    BackendWriterUpdated: TypedContractEvent<
      BackendWriterUpdatedEvent.InputTuple,
      BackendWriterUpdatedEvent.OutputTuple,
      BackendWriterUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
