/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuditTrail } from "./AuditTrail";
export * as factories from "./factories";
export { AuditTrail__factory } from "./factories/AuditTrail__factory";
